### ISSUE TITLE
initialSelectedName works weirdly

### ISSUE THREAD

**Issue by outaTiME** [richardvclam/react-native-resegmented-control#1]
Hi Richard im getting into it:

If i set `initialSelectedName` the seletion gets stuck in that item and on the other hand if the `initialSelectedName` is took from state does not make the sliding animation.

Here the snippet:

```js
state = {
  currencyIndex: 0,
};

_handleCurrencyIndexChange = index => {
  this.setState({
    currencyIndex: Helper.getNumberValue(index),
  });
};

<StyledSegmentedControl
  theme={theme}
  // from state way
  // initialSelectedName={this.state.currencyIndex.toString()}
  initialSelectedName="0"
  onChangeValue={this._handleCurrencyIndexChange}>
  <Segment name="0" content="OPT #1" />
  <Segment name="1" content="OPT #2" />
</StyledSegmentedControl>
```

Thanks !!!

**Comment by richardvclam** [comment]
I'll look into this. Thanks for reporting!

**Comment by richardvclam** [comment]
@outaTiME, I've pushed out a fix. Let me know if you're still running into the issue.

**Comment by outaTiME** [comment]
Wow, great news !!

thanks i will try in a while 👍
