### ISSUE TITLE
Add to curated lists

### ISSUE THREAD

**Issue by Noitidart** [richardvclam/react-native-resegmented-control#2]
I had a hard time finding this lib.

* [x] https://js.coach/ ----- https://github.com/jscoach/support/issues/998
* [x] https://www.native.directory/ ----- https://github.com/react-native-community/react-native-directory/pull/226

Any others?

**Comment by richardvclam** [comment]
❤️

**Comment by Noitidart** [comment]
:D :D :D

**Comment by Noitidart** [comment]
js.coach just merged. closing
