### ISSUE TITLE
Feature Request: Enable Passing Icons to Segments

### ISSUE THREAD

**Issue by jakebern** [richardvclam/react-native-resegmented-control#9]
Thanks for this great library. Native animation support for both iOS and Android is awesome!

Feature request to enable using icons in each segment, ideas:
- Enable setting icon per segment
- Allow providing custom component to each Segment (instead of just a text string)

**Comment by jakebern** [comment]
Closing this, as you do support this, I just wasn't explicitly passing props down :).
https://github.com/richardvclam/react-native-resegmented-control/blob/master/src/Segment/Segment.tsx#L65

Thanks!

**Comment by richardvclam** [comment]
Hi @jakebern! Thank for using the library.

I was just in the middle of drafting a reply back to you. Yes the library does support it however it's not properly documented (this is my fault, apologies) 😅 . I'll work on updating the documentation so there won't be any confusion in the future 😄
